// Full confirmed 2026 Masters Tournament field
// Source: Augusta National official field + Golf.com + Sky Sports (April 2026)
// Note: Tiger Woods and Phil Mickelson are NOT in the 2026 field

export function staticPlayersAsScores() {
  const field = [
    // Top contenders
    "Scottie Scheffler",
    "Rory McIlroy",
    "Ludvig Åberg",
    "Cameron Young",
    "Matt Fitzpatrick",
    "Xander Schauffele",
    "Bryson DeChambeau",
    "Jon Rahm",
    "Tommy Fleetwood",
    "Collin Morikawa",
    "Viktor Hovland",
    "Shane Lowry",
    "Chris Gotterup",
    "Nicolai Højgaard",
    "Jordan Spieth",
    "Adam Scott",
    "Patrick Cantlay",
    "J.J. Spaun",
    "Dustin Johnson",
    "Brooks Koepka",
    "Hideki Matsuyama",
    "Tom Kim",
    "Robert MacIntyre",
    "Joaquin Niemann",
    "Min Woo Lee",
    "Justin Thomas",
    "Patrick Reed",
    "Sepp Straka",
    "Corey Conners",
    "Tony Finau",
    "Russell Henley",
    "Sahith Theegala",
    "Cameron Smith",
    "Tyrrell Hatton",
    "Jason Day",
    "Max Homa",
    "Sungjae Im",
    "Harris English",
    "Alex Noren",
    "Sam Burns",
    "Brian Harman",
    "Wyndham Clark",
    "Kurt Kitayama",
    "Nick Taylor",
    "Ryan Fox",
    "Ben Griffin",
    "Carlos Ortiz",
    "Haotong Li",
    "Sam Stevens",
    "Casey Jarvis",
    "Johnny Keefer",
    "Max Greyserman",
    "Michael Brennan",
    "Akshay Bhatia",
    "Davis Thompson",
    "Nick Dunlap",
    "Rasmus Højgaard",
    "Matthieu Pavon",
    "Thomas Detry",
    "Jacob Bridgeman",
    "Keegan Bradley",
    "Billy Horschel",
    "Christiaan Bezuidenhout",
    "Chris Kirk",
    "Keith Mitchell",
    // Late qualifiers (Houston Open + OWGR top 50)
    "Gary Woodland",
    "Daniel Berger",
    "Jake Knapp",
    "Matt McCarty",
    // Past champions (competing)
    "Bubba Watson",
    "Sergio Garcia",
    "Fred Couples",
    "Mike Weir",
    "Vijay Singh",
    "Trevor Immelman",
    "Charl Schwartzel",
    "Danny Willett",
    "Francesco Molinari",
    "Bernhard Langer",
    "Sandy Lyle",
    "Larry Mize",
    "José María Olazábal",
    "Mark O'Meara",
    "Zach Johnson",
    // Amateurs
    "Jackson Herrington",
    "Aldrich Potgieter",
    "Neal Shipley",
    "Luke Potter",
    "Chase Johnson",
    "Connor Graham",
  ];

  return field.map(name => ({
    name,
    espnId: "",
    headshot: null as string | null,
    totalScore: 0,
    position: "",
    status: "active",
    r1: null as number | null,
    r2: null as number | null,
    r3: null as number | null,
    r4: null as number | null,
    teeTime: null as string | null,
    thru: null as string | null,
  }));
}
