export const GOLFERS = [
  "Scottie Scheffler",
  "Rory McIlroy",
  "Jon Rahm",
  "Xander Schauffele",
  "Ludvig Åberg",
  "Collin Morikawa",
  "Viktor Hovland",
  "Tommy Fleetwood",
  "Brooks Koepka",
  "Justin Thomas",
  "Patrick Cantlay",
  "Will Zalatoris",
  "Shane Lowry",
  "Tony Finau",
  "Hideki Matsuyama",
  "Max Homa",
  "Russell Henley",
  "Adam Scott",
  "Cameron Smith",
  "Dustin Johnson",
  "Bryson DeChambeau",
  "Jordan Spieth",
  "Matt Fitzpatrick",
  "Tyrrell Hatton",
  "Robert MacIntyre",
  "Tom Kim",
  "Sahith Theegala",
  "Sungjae Im",
  "Akshay Bhatia",
  "Min Woo Lee",
];
