// Full 2026 PGA Championship field — Aronimink Golf Club
// Used as guaranteed fallback when ESPN is unavailable

export function staticPlayersAsScores() {
  const field = [
    // Top contenders
    "Scottie Scheffler",
    "Rory McIlroy",
    "Xander Schauffele",
    "Collin Morikawa",
    "Bryson DeChambeau",
    "Ludvig Åberg",
    "Tommy Fleetwood",
    "Viktor Hovland",
    "Jon Rahm",
    "Shane Lowry",
    "Patrick Cantlay",
    "Justin Thomas",
    "Jordan Spieth",
    "Tony Finau",
    "Russell Henley",
    "Sahith Theegala",
    "Brooks Koepka",
    "Max Homa",
    "Sungjae Im",
    "Harris English",
    "Keegan Bradley",
    "Billy Horschel",
    "Brian Harman",
    "Wyndham Clark",
    "Tom Kim",
    "Hideki Matsuyama",
    "Robert MacIntyre",
    "Min Woo Lee",
    "Joaquin Niemann",
    "Tyrrell Hatton",
    "Jason Day",
    "Matt Fitzpatrick",
    "Corey Conners",
    "Sepp Straka",
    "Sam Burns",
    "Nick Taylor",
    "Ryan Fox",
    "Alex Noren",
    "Kurt Kitayama",
    "Akshay Bhatia",
    "Davis Thompson",
    "Nick Dunlap",
    "Rasmus Højgaard",
    "Nicolai Højgaard",
    "Matthieu Pavon",
    "Thomas Detry",
    "Jacob Bridgeman",
    "Chris Kirk",
    "Keith Mitchell",
    "Ben Griffin",
    "Christiaan Bezuidenhout",
    "Carlos Ortiz",
    "Haotong Li",
    "Max Greyserman",
    "Sam Stevens",
    "Michael Brennan",
    "Adam Scott",
    "Patrick Reed",
    "Cameron Young",
    "Cameron Smith",
    "Dustin Johnson",
    "Bubba Watson",
    "Sergio Garcia",
    "J.J. Spaun",
    "Harris English",
    "Denny McCarthy",
    "Eric Cole",
    "Taylor Moore",
    "Austin Eckroat",
    "Byeong Hun An",
    "Chris Gotterup",
    "Jake Knapp",
    "Maverick McNealy",
    "Andrew Novak",
    "Aaron Rai",
    "David Skinns",
    "Thriston Lawrence",
    "Justin Rose",
    "Zach Johnson",
    "Rickie Fowler",
    "Gary Woodland",
    "Adam Hadwin",
    "Nate Lashley",
    "Luke Donald",
    "Richard Bland",
    "Aldrich Potgieter",
    "Neal Shipley",
    "Jackson Herrington",
    "Connor Graham",
    "Luke Potter",
  ].filter((v, i, a) => a.indexOf(v) === i); // deduplicate

  return field.map(name => ({
    name,
    espnId: "",
    headshot: null as string | null,
    totalScore: 0,
    position: "",
    status: "active",
    r1: null as number | null,
    r2: null as number | null,
    r3: null as number | null,
    r4: null as number | null,
    teeTime: null as string | null,
    thru: null as string | null,
  }));
}
