// Full 2026 PGA Championship field — Aronimink Golf Club
// Used as guaranteed fallback when ESPN is unavailable

export function staticPlayersAsScores() {
  const field = [
    // Top contenders
    "Scottie Scheffler",
    "Rory McIlroy",
    "Xander Schauffele",
    "Collin Morikawa",
    "Bryson DeChambeau",
    "Ludvig Åberg",
    "Tommy Fleetwood",
    "Viktor Hovland",
    "Jon Rahm",
    "Shane Lowry",
    "Patrick Cantlay",
    "Justin Thomas",
    "Jordan Spieth",
    "Tony Finau",
    "Russell Henley",
    "Sahith Theegala",
    "Brooks Koepka",
    "Max Homa",
    "Sungjae Im",
    "Harris English",
    "Keegan Bradley",
    "Billy Horschel",
    "Brian Harman",
    "Wyndham Clark",
    "Tom Kim",
    "Hideki Matsuyama",
    "Robert MacIntyre",
    "Min Woo Lee",
    "Joaquin Niemann",
    "Tyrrell Hatton",
    "Jason Day",
    "Matt Fitzpatrick",
    "Corey Conners",
    "Sepp Straka",
    "Sam Burns",
    "Nick Taylor",
    "Ryan Fox",
    "Alex Noren",
    "Kurt Kitayama",
    "Akshay Bhatia",
    "Davis Thompson",
    "Nick Dunlap",
    "Rasmus Højgaard",
    "Nicolai Højgaard",
    "Matthieu Pavon",
    "Thomas Detry",
    "Jacob Bridgeman",
    "Chris Kirk",
    "Keith Mitchell",
    "Ben Griffin",
    "Christiaan Bezuidenhout",
    "Carlos Ortiz",
    "Haotong Li",
    "Max Greyserman",
    "Sam Stevens",
    "Michael Brennan",
    "Adam Scott",
    "Patrick Reed",
    "Cameron Young",
    "Cameron Smith",
    "Dustin Johnson",
    "Bubba Watson",
    "Sergio Garcia",
    "J.J. Spaun",
    "Harris English",
    "Denny McCarthy",
    "Eric Cole",
    "Taylor Moore",
    "Austin Eckroat",
    "Byeong Hun An",
    "Chris Gotterup",
    "Jake Knapp",
    "Maverick McNealy",
    "Andrew Novak",
    "Aaron Rai",
    "David Skinns",
    "Thriston Lawrence",
    "Justin Rose",
    "Zach Johnson",
    "Rickie Fowler",
    "Gary Woodland",
    "Adam Hadwin",
    "Nate Lashley",
    "Luke Donald",
    "Richard Bland",
    "Aldrich Potgieter",
    "Neal Shipley",
    "Jackson Herrington",
    "Connor Graham",
    "Luke Potter",
  ].filter((v, i, a) => a.indexOf(v) === i); // deduplicate

  return field.map(name => ({
    name,
    espnId: "",
    headshot: null as string | null,
    totalScore: 0,
    position: "",
    status: "active",
    r1: null as number | null,
    r2: null as number | null,
    r3: null as number | null,
    r4: null as number | null,
    teeTime: null as string | null,
    thru: null as string | null,
  }));
}

// Current OWGR rankings for 2026 PGA Championship field (approx. May 2026)
export const OWGR_RANKINGS: Record<string, number> = {
  "Scottie Scheffler": 1,
  "Rory McIlroy": 2,
  "Xander Schauffele": 3,
  "Collin Morikawa": 4,
  "Ludvig Åberg": 5,
  "Tommy Fleetwood": 6,
  "Jon Rahm": 7,
  "Bryson DeChambeau": 8,
  "Viktor Hovland": 9,
  "Shane Lowry": 10,
  "Patrick Cantlay": 11,
  "Justin Thomas": 12,
  "Jordan Spieth": 13,
  "Brooks Koepka": 14,
  "Hideki Matsuyama": 15,
  "Tony Finau": 16,
  "Russell Henley": 17,
  "Robert MacIntyre": 18,
  "Min Woo Lee": 19,
  "Joaquin Niemann": 20,
  "Sahith Theegala": 21,
  "Tom Kim": 22,
  "Matt Fitzpatrick": 23,
  "Tyrrell Hatton": 24,
  "Jason Day": 25,
  "Sungjae Im": 26,
  "Max Homa": 27,
  "Sepp Straka": 28,
  "Sam Burns": 29,
  "Corey Conners": 30,
  "Cameron Young": 31,
  "Akshay Bhatia": 32,
  "Nick Dunlap": 33,
  "Rasmus Højgaard": 34,
  "Wyndham Clark": 35,
  "Brian Harman": 36,
  "Harris English": 37,
  "Matthieu Pavon": 38,
  "Nicolai Højgaard": 39,
  "Ryan Fox": 40,
  "Thomas Detry": 41,
  "Kurt Kitayama": 42,
  "Nick Taylor": 43,
  "Alex Noren": 44,
  "Davis Thompson": 45,
  "Cameron Smith": 46,
  "Dustin Johnson": 47,
  "Adam Scott": 48,
  "Patrick Reed": 49,
  "Jacob Bridgeman": 50,
  "Christiaan Bezuidenhout": 51,
  "Billy Horschel": 52,
  "Keegan Bradley": 53,
  "Chris Kirk": 54,
  "Ben Griffin": 55,
  "Keith Mitchell": 56,
  "Max Greyserman": 57,
  "Carlos Ortiz": 58,
  "Haotong Li": 59,
  "Sam Stevens": 60,
  "Michael Brennan": 61,
  "Chris Gotterup": 62,
  "Jake Knapp": 63,
  "Aaron Rai": 64,
  "Byeong Hun An": 65,
  "Austin Eckroat": 66,
  "Maverick McNealy": 67,
  "Andrew Novak": 68,
  "J.J. Spaun": 69,
  "Justin Rose": 70,
  "Rickie Fowler": 71,
  "Denny McCarthy": 72,
  "Eric Cole": 73,
  "Taylor Moore": 74,
  "Adam Hadwin": 75,
  "Gary Woodland": 76,
  "Zach Johnson": 77,
  "Bubba Watson": 110,
  "Sergio Garcia": 120,
  "Aldrich Potgieter": 140,
  "Neal Shipley": 200,
  "Jackson Herrington": 210,
  "Connor Graham": 220,
  "Luke Potter": 230,
};
